[package]
name = "pretty_midi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
itertools = "0.10"
log = "0.4"
midly = "0.5"
once_cell = "1.10"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
